repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.5
    hooks:
      - id: ruff
        args: ["--fix", "--unsafe-fixes"]
        additional_dependencies: []
      - id: ruff-format
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: ["--in-place", "--remove-all-unused-imports", "--remove-unused-variables", "-r", "backend/src"]
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        additional_dependencies: ["pyflakes>=3.2.0", "pycodestyle>=2.12.0"]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
      - id: bandit
        args: ["-r", "backend/src", "-q"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args: ["--write"]
        additional_dependencies: ["prettier@3.3.3"]