version: '3.9'

services:
  # CIではvllmサービス自体を軽量モックに置き換える
  vllm:
    image: hashicorp/http-echo:0.2.3
    command: ["-listen=:8001", "-text={\"model\":\"mock\",\"engine\":\"mock\",\"status\":\"ok\"}"]
    networks:
      - shodo-internal
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:8001 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  backend:
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      vllm:
        condition: service_healthy

networks:
  shodo-internal:
    external: false
