line-length = 120
indent-width = 4
select = ["F", "E", "B", "I", "W", "BLE", "S"]
ignore = []
exclude = [
  ".venv",
  "node_modules",
  "frontend/node_modules",
  "backend/node_modules",
]

[per-file-ignores]
# テストでは print や assert を許容
"backend/src/tests/**/*.py" = ["S101", "T201"]