name: Backend CI (docker-compose)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  DOCKER_BUILDKIT: "1"
  COMPOSE_FILE: shodo-ecosystem/docker-compose.yml

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Docker versions
        run: |
          docker --version || true
          docker compose version || true
          docker-compose --version || true

      - name: Ensure docker compose available
        run: |
          set -e
          if docker compose version >/dev/null 2>&1; then
            echo "COMPOSE=docker compose" >> $GITHUB_ENV
          elif docker-compose --version >/dev/null 2>&1; then
            echo "COMPOSE=docker-compose" >> $GITHUB_ENV
          else
            sudo apt-get update
            sudo apt-get install -y docker-compose-plugin
            if docker compose version >/dev/null 2>&1; then
              echo "COMPOSE=docker compose" >> $GITHUB_ENV
            else
              echo "docker compose is still unavailable" >&2
              exit 1
            fi
          fi

      - name: Verify repository structure
        run: |
          ls -la
          ls -la shodo-ecosystem || true
          ls -la shodo-ecosystem/backend || true
          ls -la shodo-ecosystem/ai-server || true
          test -f shodo-ecosystem/docker-compose.yml

      - name: Create backend .env (development-like)
        run: |
          mkdir -p shodo-ecosystem/backend
          cat > shodo-ecosystem/backend/.env <<'EOF'
          ENVIRONMENT=development
          DEBUG=true
          HOST=0.0.0.0
          PORT=8000
          CORS_ORIGINS=http://localhost:3000
          JWT_SECRET_KEY=dev-secret
          ENCRYPTION_KEY=dev-encryption
          VLLM_URL=http://vllm:8001
          LPR_ENFORCER_ENABLED=true
          ALLOW_LPR_TOKEN_QUERY=false
          EOF
          echo "---- compose file head ----"
          sed -n '1,80p' shodo-ecosystem/docker-compose.yml || true
          echo "---------------------------"

      - name: Build images (backend, vllm)
        working-directory: shodo-ecosystem
        run: |
          set -e
          $COMPOSE build --progress=plain backend vllm

      - name: Start infra and backend
        working-directory: shodo-ecosystem
        run: |
          set -e
          $COMPOSE up -d postgres redis vllm backend
          echo "Waiting for backend health..."
          BID=$($COMPOSE ps -q backend)
          for i in {1..60}; do
            STATUS=$(docker inspect -f '{{.State.Health.Status}}' "$BID" 2>/dev/null || echo "starting")
            echo "backend health: $STATUS"
            if [ "$STATUS" = "healthy" ]; then
              break
            fi
            sleep 2
          done
          $COMPOSE ps
          echo "Recent backend logs:"
          $COMPOSE logs --no-color --tail=80 backend || true

      - name: Run LPR tests inside backend container
        working-directory: shodo-ecosystem
        run: |
          set -e
          $COMPOSE exec -T backend pytest -q tests/test_lpr_system.py

      - name: Show backend logs (on failure)
        if: failure()
        working-directory: shodo-ecosystem
        run: |
          $COMPOSE ps || true
          $COMPOSE logs --no-color backend || true

      - name: Teardown
        if: always()
        working-directory: shodo-ecosystem
        run: |
          $COMPOSE down -v || true
