name: Backend CI (docker-compose)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  DOCKER_BUILDKIT: "1"
  COMPOSE_FILE: shodo-ecosystem/docker-compose.yml

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker versions
        run: |
          docker --version
          docker compose version

      - name: Create backend .env (development-like)
        run: |
          cat > shodo-ecosystem/backend/.env <<'EOF'
          ENVIRONMENT=development
          DEBUG=true
          HOST=0.0.0.0
          PORT=8000
          CORS_ORIGINS=http://localhost:3000
          JWT_SECRET_KEY=dev-secret
          ENCRYPTION_KEY=dev-encryption
          VLLM_URL=http://vllm:8001
          LPR_ENFORCER_ENABLED=true
          ALLOW_LPR_TOKEN_QUERY=false
          EOF

      - name: Build images
        working-directory: shodo-ecosystem
        run: |
          docker compose build backend vllm

      - name: Start infra and backend
        working-directory: shodo-ecosystem
        run: |
          set -e
          docker compose up -d postgres redis vllm backend
          echo "Waiting for backend health..."
          BID=$(docker compose ps -q backend)
          for i in {1..60}; do
            STATUS=$(docker inspect -f '{{.State.Health.Status}}' "$BID" || echo "starting")
            if [ "$STATUS" = "healthy" ]; then
              echo "backend is healthy"
              break
            fi
            sleep 2
          done
          docker compose ps

      - name: Run LPR tests inside backend container
        working-directory: shodo-ecosystem
        run: |
          docker compose exec -T backend pytest -q tests/test_lpr_system.py

      - name: Show backend logs (on failure)
        if: failure()
        working-directory: shodo-ecosystem
        run: |
          docker compose logs --no-color backend | tail -n 400 || true

      - name: Teardown
        if: always()
        working-directory: shodo-ecosystem
        run: |
          docker compose down -v