name: Backend CI (docker-compose)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  DOCKER_BUILDKIT: "1"

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure docker compose available
        run: |
          set -e
          if docker compose version >/dev/null 2>&1; then
            echo "COMPOSE=docker compose" >> $GITHUB_ENV
          elif docker-compose --version >/dev/null 2>&1; then
            echo "COMPOSE=docker-compose" >> $GITHUB_ENV
          else
            sudo apt-get update
            sudo apt-get install -y docker-compose-plugin
            docker compose version
            echo "COMPOSE=docker compose" >> $GITHUB_ENV
          fi

      - name: Verify repository structure
        run: |
          ls -la
          ls -la shodo-ecosystem || true
          test -f shodo-ecosystem/docker-compose.yml

      - name: Create backend .env (development-like)
        run: |
          cat > shodo-ecosystem/backend/.env <<'EOF'
          ENVIRONMENT=development
          DEBUG=true
          HOST=0.0.0.0
          PORT=8000
          CORS_ORIGINS=http://localhost:3000
          JWT_SECRET_KEY=dev-secret
          ENCRYPTION_KEY=dev-encryption
          VLLM_URL=http://vllm:8001
          LPR_ENFORCER_ENABLED=true
          ALLOW_LPR_TOKEN_QUERY=false
          EOF

      - name: Validate compose config
        working-directory: shodo-ecosystem
        run: |
          $COMPOSE -f docker-compose.yml -f docker-compose.ci.yml config

      - name: Build images (backend only for CI)
        working-directory: shodo-ecosystem
        run: |
          set -e
          echo "----- Dockerfile (backend) head -----"
          sed -n '1,120p' backend/Dockerfile || true
          echo "----- requirements (backend) head -----"
          sed -n '1,120p' backend/requirements.txt || true
          $COMPOSE -f docker-compose.yml -f docker-compose.ci.yml build --progress=plain backend

      - name: Start infra and backend (with vllm-mock)
        working-directory: shodo-ecosystem
        run: |
          set -e
          $COMPOSE -f docker-compose.yml -f docker-compose.ci.yml up -d postgres redis vllm-mock backend
          echo "Waiting for backend health..."
          BID=$($COMPOSE -f docker-compose.yml -f docker-compose.ci.yml ps -q backend)
          for i in {1..60}; do
            STATUS=$(docker inspect -f '{{.State.Health.Status}}' "$BID" 2>/dev/null || echo "starting")
            echo "backend health: $STATUS"
            if [ "$STATUS" = "healthy" ]; then break; fi
            sleep 2
          done
          $COMPOSE -f docker-compose.yml -f docker-compose.ci.yml ps
          $COMPOSE -f docker-compose.yml -f docker-compose.ci.yml logs --no-color --tail=120 backend || true

      - name: Run LPR tests inside backend container
        working-directory: shodo-ecosystem
        run: |
          set -e
          $COMPOSE -f docker-compose.yml -f docker-compose.ci.yml exec -T backend pytest -q tests/test_lpr_system.py

      - name: Show backend logs (on failure)
        if: failure()
        working-directory: shodo-ecosystem
        run: |
          $COMPOSE -f docker-compose.yml -f docker-compose.ci.yml ps || true
          $COMPOSE -f docker-compose.yml -f docker-compose.ci.yml logs --no-color backend || true

      - name: Teardown
        if: always()
        working-directory: shodo-ecosystem
        run: |
          $COMPOSE -f docker-compose.yml -f docker-compose.ci.yml down -v || true
